apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  # hostPath:
  #   path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

--
# #docker run --rm --entrypoint htpasswd registry:2.7.0 -Bbn USERNAME PASSWORD > htpasswd
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: create-auth
# spec:
#   template:
#     spec:
#       containers:
#       - name: auth
#         image: registry:latest
#         command: ["htpasswd"]
#         argumants: 
#           - "-Bbn"
#           - "jay" 
#           - "jay"
#           - ">"
#           - "htpasswd"
#         volumeMounts:
#         - mountPath: "/auth"
#           name: auth-pv-storage
#       restartPolicy: Never
#       volumes:
#         - name: auth-pv-storage
#           persistentVolumeClaim:
#             claimName: auth-pv-claim      
#   backoffLimit: 4