# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     kubernetes.io/metadata.name: registry
#   name: registry
# ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth
  namespace: registry
data:
  htpasswd: |
    admin:$2y$05$VCxq5CnvHQEePXQ6P/NzDuNg5gCLvSKrvlnODixJA0YzEabvyCB.W
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:latest
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
            # - name: REGISTRY_HTTP_TLS_CERTIFICATE
            #   value: "/certs/cert.pem"
            # - name: REGISTRY_HTTP_TLS_KEY
            #   value: "/certs/key.pem"
            # - name: REGISTRY_HTTP_TLS_CLIENTCAS_0
            #   value: "/certs/ca.pem"
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"        
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
          volumeMounts:
            - mountPath: "/certs"
              name: "root-certs"
            - name: auth
              mountPath: /auth
      volumes:
        - name: registry
          emptyDir: {}
        - name: "root-certs"
          secret:
            secretName: "root-secret"
            items:
              - key: "tls.crt"
                path: "cert.pem"
              - key: "tls.key"
                path: "key.pem"
              - key: "ca.crt"
                path: "ca.pem"
        - name: auth
          configMap:
            name: auth                
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: registry
  sessionAffinity: None
  type: ClusterIP
