apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kc-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: kc.fbi.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  kc
                port:
                  number: 8080             
---
apiVersion: v1
kind: Service
metadata:
  name: kc
  labels:
    app: kc
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http-uaa
    targetPort: 8080
    protocol: TCP
  selector:
    app: kc-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kc-deployment
  template:
    metadata:
      labels:
        app: kc-deployment
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.1.2
        args: ["start-dev"]
        resources: {}
        readinessProbe:
          httpGet:
            path: "/health/ready"
            port: 9000        
        ports:
        - name: http-uaa
          containerPort: 8080
          protocol: TCP        
        env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "admin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "4GemnfireIsGreat!"
        - name: KC_HEALTH_ENABLED
          value: "true"          
      #   volumeMounts:
      #   - name: uaa-config
      #     mountPath: /uaa
      #     readOnly: true
      # volumes:
      # - name: uaa-config
      #   configMap:
      #     name: uaa-config
      #     items:
      #     - key: uaa.yml
      #       path: uaa.yml

